package com.pursebao.commons.pojo.po;

import java.io.Serializable;

public class Account implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.aid
     *
     * @mbggenerated
     */
    private String aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_amount
     *
     * @mbggenerated
     */
    private Double accountAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.expected_capital
     *
     * @mbggenerated
     */
    private Double expectedCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.expected_totalincrease
     *
     * @mbggenerated
     */
    private Double expectedTotalincrease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.cash_amount
     *
     * @mbggenerated
     */
    private Double cashAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.daily_totalincrease
     *
     * @mbggenerated
     */
    private Double dailyTotalincrease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.totalincreasement
     *
     * @mbggenerated
     */
    private Double totalincreasement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.current_total_increase
     *
     * @mbggenerated
     */
    private Double currentTotalIncrease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.aid
     *
     * @return the value of account.aid
     *
     * @mbggenerated
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.aid
     *
     * @param aid the value for account.aid
     *
     * @mbggenerated
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_amount
     *
     * @return the value of account.account_amount
     *
     * @mbggenerated
     */
    public Double getAccountAmount() {
        return accountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_amount
     *
     * @param accountAmount the value for account.account_amount
     *
     * @mbggenerated
     */
    public void setAccountAmount(Double accountAmount) {
        this.accountAmount = accountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.expected_capital
     *
     * @return the value of account.expected_capital
     *
     * @mbggenerated
     */
    public Double getExpectedCapital() {
        return expectedCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.expected_capital
     *
     * @param expectedCapital the value for account.expected_capital
     *
     * @mbggenerated
     */
    public void setExpectedCapital(Double expectedCapital) {
        this.expectedCapital = expectedCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.expected_totalincrease
     *
     * @return the value of account.expected_totalincrease
     *
     * @mbggenerated
     */
    public Double getExpectedTotalincrease() {
        return expectedTotalincrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.expected_totalincrease
     *
     * @param expectedTotalincrease the value for account.expected_totalincrease
     *
     * @mbggenerated
     */
    public void setExpectedTotalincrease(Double expectedTotalincrease) {
        this.expectedTotalincrease = expectedTotalincrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.cash_amount
     *
     * @return the value of account.cash_amount
     *
     * @mbggenerated
     */
    public Double getCashAmount() {
        return cashAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.cash_amount
     *
     * @param cashAmount the value for account.cash_amount
     *
     * @mbggenerated
     */
    public void setCashAmount(Double cashAmount) {
        this.cashAmount = cashAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.daily_totalincrease
     *
     * @return the value of account.daily_totalincrease
     *
     * @mbggenerated
     */
    public Double getDailyTotalincrease() {
        return dailyTotalincrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.daily_totalincrease
     *
     * @param dailyTotalincrease the value for account.daily_totalincrease
     *
     * @mbggenerated
     */
    public void setDailyTotalincrease(Double dailyTotalincrease) {
        this.dailyTotalincrease = dailyTotalincrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.totalincreasement
     *
     * @return the value of account.totalincreasement
     *
     * @mbggenerated
     */
    public Double getTotalincreasement() {
        return totalincreasement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.totalincreasement
     *
     * @param totalincreasement the value for account.totalincreasement
     *
     * @mbggenerated
     */
    public void setTotalincreasement(Double totalincreasement) {
        this.totalincreasement = totalincreasement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.current_total_increase
     *
     * @return the value of account.current_total_increase
     *
     * @mbggenerated
     */
    public Double getCurrentTotalIncrease() {
        return currentTotalIncrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.current_total_increase
     *
     * @param currentTotalIncrease the value for account.current_total_increase
     *
     * @mbggenerated
     */
    public void setCurrentTotalIncrease(Double currentTotalIncrease) {
        this.currentTotalIncrease = currentTotalIncrease;
    }
}