package com.pursebao.commons.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class ContentCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_category.caid
     *
     * @mbggenerated
     */
    private String caid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_category.cate_name
     *
     * @mbggenerated
     */
    private String cateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_category.cate_status
     *
     * @mbggenerated
     */
    private Integer cateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_category.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_category.is_parent
     *
     * @mbggenerated
     */
    private Integer isParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_category.cate_created
     *
     * @mbggenerated
     */
    private Date cateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_category.cate_updated
     *
     * @mbggenerated
     */
    private Date cateUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_category
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_category.caid
     *
     * @return the value of content_category.caid
     *
     * @mbggenerated
     */
    public String getCaid() {
        return caid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_category.caid
     *
     * @param caid the value for content_category.caid
     *
     * @mbggenerated
     */
    public void setCaid(String caid) {
        this.caid = caid == null ? null : caid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_category.cate_name
     *
     * @return the value of content_category.cate_name
     *
     * @mbggenerated
     */
    public String getCateName() {
        return cateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_category.cate_name
     *
     * @param cateName the value for content_category.cate_name
     *
     * @mbggenerated
     */
    public void setCateName(String cateName) {
        this.cateName = cateName == null ? null : cateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_category.cate_status
     *
     * @return the value of content_category.cate_status
     *
     * @mbggenerated
     */
    public Integer getCateStatus() {
        return cateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_category.cate_status
     *
     * @param cateStatus the value for content_category.cate_status
     *
     * @mbggenerated
     */
    public void setCateStatus(Integer cateStatus) {
        this.cateStatus = cateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_category.parent_id
     *
     * @return the value of content_category.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_category.parent_id
     *
     * @param parentId the value for content_category.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_category.is_parent
     *
     * @return the value of content_category.is_parent
     *
     * @mbggenerated
     */
    public Integer getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_category.is_parent
     *
     * @param isParent the value for content_category.is_parent
     *
     * @mbggenerated
     */
    public void setIsParent(Integer isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_category.cate_created
     *
     * @return the value of content_category.cate_created
     *
     * @mbggenerated
     */
    public Date getCateCreated() {
        return cateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_category.cate_created
     *
     * @param cateCreated the value for content_category.cate_created
     *
     * @mbggenerated
     */
    public void setCateCreated(Date cateCreated) {
        this.cateCreated = cateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_category.cate_updated
     *
     * @return the value of content_category.cate_updated
     *
     * @mbggenerated
     */
    public Date getCateUpdated() {
        return cateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_category.cate_updated
     *
     * @param cateUpdated the value for content_category.cate_updated
     *
     * @mbggenerated
     */
    public void setCateUpdated(Date cateUpdated) {
        this.cateUpdated = cateUpdated;
    }
}