package com.pursebao.commons.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class Content implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.conid
     *
     * @mbggenerated
     */
    private String conid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.cate_id
     *
     * @mbggenerated
     */
    private String cateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.title_desc
     *
     * @mbggenerated
     */
    private String titleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.cate_created
     *
     * @mbggenerated
     */
    private Date cateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.cate_updated
     *
     * @mbggenerated
     */
    private Date cateUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.context
     *
     * @mbggenerated
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.conid
     *
     * @return the value of content.conid
     *
     * @mbggenerated
     */
    public String getConid() {
        return conid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.conid
     *
     * @param conid the value for content.conid
     *
     * @mbggenerated
     */
    public void setConid(String conid) {
        this.conid = conid == null ? null : conid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.cate_id
     *
     * @return the value of content.cate_id
     *
     * @mbggenerated
     */
    public String getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.cate_id
     *
     * @param cateId the value for content.cate_id
     *
     * @mbggenerated
     */
    public void setCateId(String cateId) {
        this.cateId = cateId == null ? null : cateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.title
     *
     * @return the value of content.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.title
     *
     * @param title the value for content.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.title_desc
     *
     * @return the value of content.title_desc
     *
     * @mbggenerated
     */
    public String getTitleDesc() {
        return titleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.title_desc
     *
     * @param titleDesc the value for content.title_desc
     *
     * @mbggenerated
     */
    public void setTitleDesc(String titleDesc) {
        this.titleDesc = titleDesc == null ? null : titleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.pic
     *
     * @return the value of content.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.pic
     *
     * @param pic the value for content.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.cate_created
     *
     * @return the value of content.cate_created
     *
     * @mbggenerated
     */
    public Date getCateCreated() {
        return cateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.cate_created
     *
     * @param cateCreated the value for content.cate_created
     *
     * @mbggenerated
     */
    public void setCateCreated(Date cateCreated) {
        this.cateCreated = cateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.cate_updated
     *
     * @return the value of content.cate_updated
     *
     * @mbggenerated
     */
    public Date getCateUpdated() {
        return cateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.cate_updated
     *
     * @param cateUpdated the value for content.cate_updated
     *
     * @mbggenerated
     */
    public void setCateUpdated(Date cateUpdated) {
        this.cateUpdated = cateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.context
     *
     * @return the value of content.context
     *
     * @mbggenerated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.context
     *
     * @param context the value for content.context
     *
     * @mbggenerated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}