package com.pursebao.commons.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class Contract implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.con_id
     *
     * @mbggenerated
     */
    private String conId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.con_name
     *
     * @mbggenerated
     */
    private String conName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.con_begintime
     *
     * @mbggenerated
     */
    private Date conBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.con_endtime
     *
     * @mbggenerated
     */
    private Date conEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.loan_uid
     *
     * @mbggenerated
     */
    private String loanUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.invest_uid
     *
     * @mbggenerated
     */
    private String investUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.con_content
     *
     * @mbggenerated
     */
    private String conContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.con_id
     *
     * @return the value of contract.con_id
     *
     * @mbggenerated
     */
    public String getConId() {
        return conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.con_id
     *
     * @param conId the value for contract.con_id
     *
     * @mbggenerated
     */
    public void setConId(String conId) {
        this.conId = conId == null ? null : conId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.con_name
     *
     * @return the value of contract.con_name
     *
     * @mbggenerated
     */
    public String getConName() {
        return conName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.con_name
     *
     * @param conName the value for contract.con_name
     *
     * @mbggenerated
     */
    public void setConName(String conName) {
        this.conName = conName == null ? null : conName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.con_begintime
     *
     * @return the value of contract.con_begintime
     *
     * @mbggenerated
     */
    public Date getConBegintime() {
        return conBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.con_begintime
     *
     * @param conBegintime the value for contract.con_begintime
     *
     * @mbggenerated
     */
    public void setConBegintime(Date conBegintime) {
        this.conBegintime = conBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.con_endtime
     *
     * @return the value of contract.con_endtime
     *
     * @mbggenerated
     */
    public Date getConEndtime() {
        return conEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.con_endtime
     *
     * @param conEndtime the value for contract.con_endtime
     *
     * @mbggenerated
     */
    public void setConEndtime(Date conEndtime) {
        this.conEndtime = conEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.loan_uid
     *
     * @return the value of contract.loan_uid
     *
     * @mbggenerated
     */
    public String getLoanUid() {
        return loanUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.loan_uid
     *
     * @param loanUid the value for contract.loan_uid
     *
     * @mbggenerated
     */
    public void setLoanUid(String loanUid) {
        this.loanUid = loanUid == null ? null : loanUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.invest_uid
     *
     * @return the value of contract.invest_uid
     *
     * @mbggenerated
     */
    public String getInvestUid() {
        return investUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.invest_uid
     *
     * @param investUid the value for contract.invest_uid
     *
     * @mbggenerated
     */
    public void setInvestUid(String investUid) {
        this.investUid = investUid == null ? null : investUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.con_content
     *
     * @return the value of contract.con_content
     *
     * @mbggenerated
     */
    public String getConContent() {
        return conContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.con_content
     *
     * @param conContent the value for contract.con_content
     *
     * @mbggenerated
     */
    public void setConContent(String conContent) {
        this.conContent = conContent == null ? null : conContent.trim();
    }
}