package com.pursebao.commons.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class InvestOrders implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_orders.oid
     *
     * @mbggenerated
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_orders.invest_money
     *
     * @mbggenerated
     */
    private Double investMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_orders.invest_date
     *
     * @mbggenerated
     */
    private Date investDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_orders.invest_pid
     *
     * @mbggenerated
     */
    private String investPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_orders.investor_id
     *
     * @mbggenerated
     */
    private String investorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_orders.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invest_orders
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_orders.oid
     *
     * @return the value of invest_orders.oid
     *
     * @mbggenerated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_orders.oid
     *
     * @param oid the value for invest_orders.oid
     *
     * @mbggenerated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_orders.invest_money
     *
     * @return the value of invest_orders.invest_money
     *
     * @mbggenerated
     */
    public Double getInvestMoney() {
        return investMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_orders.invest_money
     *
     * @param investMoney the value for invest_orders.invest_money
     *
     * @mbggenerated
     */
    public void setInvestMoney(Double investMoney) {
        this.investMoney = investMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_orders.invest_date
     *
     * @return the value of invest_orders.invest_date
     *
     * @mbggenerated
     */
    public Date getInvestDate() {
        return investDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_orders.invest_date
     *
     * @param investDate the value for invest_orders.invest_date
     *
     * @mbggenerated
     */
    public void setInvestDate(Date investDate) {
        this.investDate = investDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_orders.invest_pid
     *
     * @return the value of invest_orders.invest_pid
     *
     * @mbggenerated
     */
    public String getInvestPid() {
        return investPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_orders.invest_pid
     *
     * @param investPid the value for invest_orders.invest_pid
     *
     * @mbggenerated
     */
    public void setInvestPid(String investPid) {
        this.investPid = investPid == null ? null : investPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_orders.investor_id
     *
     * @return the value of invest_orders.investor_id
     *
     * @mbggenerated
     */
    public String getInvestorId() {
        return investorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_orders.investor_id
     *
     * @param investorId the value for invest_orders.investor_id
     *
     * @mbggenerated
     */
    public void setInvestorId(String investorId) {
        this.investorId = investorId == null ? null : investorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_orders.order_status
     *
     * @return the value of invest_orders.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_orders.order_status
     *
     * @param orderStatus the value for invest_orders.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }
}