package com.pursebao.commons.pojo.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LoanExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public LoanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loan
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria implements Serializable{
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andLidIsNull() {
            addCriterion("lid is null");
            return (Criteria) this;
        }

        public Criteria andLidIsNotNull() {
            addCriterion("lid is not null");
            return (Criteria) this;
        }

        public Criteria andLidEqualTo(String value) {
            addCriterion("lid =", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidNotEqualTo(String value) {
            addCriterion("lid <>", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidGreaterThan(String value) {
            addCriterion("lid >", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidGreaterThanOrEqualTo(String value) {
            addCriterion("lid >=", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidLessThan(String value) {
            addCriterion("lid <", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidLessThanOrEqualTo(String value) {
            addCriterion("lid <=", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidLike(String value) {
            addCriterion("lid like", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidNotLike(String value) {
            addCriterion("lid not like", value, "lid");
            return (Criteria) this;
        }

        public Criteria andLidIn(List<String> values) {
            addCriterion("lid in", values, "lid");
            return (Criteria) this;
        }

        public Criteria andLidNotIn(List<String> values) {
            addCriterion("lid not in", values, "lid");
            return (Criteria) this;
        }

        public Criteria andLidBetween(String value1, String value2) {
            addCriterion("lid between", value1, value2, "lid");
            return (Criteria) this;
        }

        public Criteria andLidNotBetween(String value1, String value2) {
            addCriterion("lid not between", value1, value2, "lid");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLoanUseIsNull() {
            addCriterion("loan_use is null");
            return (Criteria) this;
        }

        public Criteria andLoanUseIsNotNull() {
            addCriterion("loan_use is not null");
            return (Criteria) this;
        }

        public Criteria andLoanUseEqualTo(String value) {
            addCriterion("loan_use =", value, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseNotEqualTo(String value) {
            addCriterion("loan_use <>", value, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseGreaterThan(String value) {
            addCriterion("loan_use >", value, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseGreaterThanOrEqualTo(String value) {
            addCriterion("loan_use >=", value, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseLessThan(String value) {
            addCriterion("loan_use <", value, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseLessThanOrEqualTo(String value) {
            addCriterion("loan_use <=", value, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseLike(String value) {
            addCriterion("loan_use like", value, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseNotLike(String value) {
            addCriterion("loan_use not like", value, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseIn(List<String> values) {
            addCriterion("loan_use in", values, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseNotIn(List<String> values) {
            addCriterion("loan_use not in", values, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseBetween(String value1, String value2) {
            addCriterion("loan_use between", value1, value2, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanUseNotBetween(String value1, String value2) {
            addCriterion("loan_use not between", value1, value2, "loanUse");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIsNull() {
            addCriterion("loan_amount is null");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIsNotNull() {
            addCriterion("loan_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLoanAmountEqualTo(Double value) {
            addCriterion("loan_amount =", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotEqualTo(Double value) {
            addCriterion("loan_amount <>", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountGreaterThan(Double value) {
            addCriterion("loan_amount >", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("loan_amount >=", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountLessThan(Double value) {
            addCriterion("loan_amount <", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountLessThanOrEqualTo(Double value) {
            addCriterion("loan_amount <=", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIn(List<Double> values) {
            addCriterion("loan_amount in", values, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotIn(List<Double> values) {
            addCriterion("loan_amount not in", values, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountBetween(Double value1, Double value2) {
            addCriterion("loan_amount between", value1, value2, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotBetween(Double value1, Double value2) {
            addCriterion("loan_amount not between", value1, value2, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeIsNull() {
            addCriterion("loan_limittime is null");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeIsNotNull() {
            addCriterion("loan_limittime is not null");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeEqualTo(Integer value) {
            addCriterion("loan_limittime =", value, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeNotEqualTo(Integer value) {
            addCriterion("loan_limittime <>", value, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeGreaterThan(Integer value) {
            addCriterion("loan_limittime >", value, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_limittime >=", value, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeLessThan(Integer value) {
            addCriterion("loan_limittime <", value, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeLessThanOrEqualTo(Integer value) {
            addCriterion("loan_limittime <=", value, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeIn(List<Integer> values) {
            addCriterion("loan_limittime in", values, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeNotIn(List<Integer> values) {
            addCriterion("loan_limittime not in", values, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeBetween(Integer value1, Integer value2) {
            addCriterion("loan_limittime between", value1, value2, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanLimittimeNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_limittime not between", value1, value2, "loanLimittime");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayIsNull() {
            addCriterion("loan_payway is null");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayIsNotNull() {
            addCriterion("loan_payway is not null");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayEqualTo(Integer value) {
            addCriterion("loan_payway =", value, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayNotEqualTo(Integer value) {
            addCriterion("loan_payway <>", value, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayGreaterThan(Integer value) {
            addCriterion("loan_payway >", value, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_payway >=", value, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayLessThan(Integer value) {
            addCriterion("loan_payway <", value, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayLessThanOrEqualTo(Integer value) {
            addCriterion("loan_payway <=", value, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayIn(List<Integer> values) {
            addCriterion("loan_payway in", values, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayNotIn(List<Integer> values) {
            addCriterion("loan_payway not in", values, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayBetween(Integer value1, Integer value2) {
            addCriterion("loan_payway between", value1, value2, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanPaywayNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_payway not between", value1, value2, "loanPayway");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsIsNull() {
            addCriterion("loan_goods is null");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsIsNotNull() {
            addCriterion("loan_goods is not null");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsEqualTo(String value) {
            addCriterion("loan_goods =", value, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsNotEqualTo(String value) {
            addCriterion("loan_goods <>", value, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsGreaterThan(String value) {
            addCriterion("loan_goods >", value, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsGreaterThanOrEqualTo(String value) {
            addCriterion("loan_goods >=", value, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsLessThan(String value) {
            addCriterion("loan_goods <", value, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsLessThanOrEqualTo(String value) {
            addCriterion("loan_goods <=", value, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsLike(String value) {
            addCriterion("loan_goods like", value, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsNotLike(String value) {
            addCriterion("loan_goods not like", value, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsIn(List<String> values) {
            addCriterion("loan_goods in", values, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsNotIn(List<String> values) {
            addCriterion("loan_goods not in", values, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsBetween(String value1, String value2) {
            addCriterion("loan_goods between", value1, value2, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanGoodsNotBetween(String value1, String value2) {
            addCriterion("loan_goods not between", value1, value2, "loanGoods");
            return (Criteria) this;
        }

        public Criteria andLoanWorthIsNull() {
            addCriterion("loan_worth is null");
            return (Criteria) this;
        }

        public Criteria andLoanWorthIsNotNull() {
            addCriterion("loan_worth is not null");
            return (Criteria) this;
        }

        public Criteria andLoanWorthEqualTo(Double value) {
            addCriterion("loan_worth =", value, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthNotEqualTo(Double value) {
            addCriterion("loan_worth <>", value, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthGreaterThan(Double value) {
            addCriterion("loan_worth >", value, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthGreaterThanOrEqualTo(Double value) {
            addCriterion("loan_worth >=", value, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthLessThan(Double value) {
            addCriterion("loan_worth <", value, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthLessThanOrEqualTo(Double value) {
            addCriterion("loan_worth <=", value, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthIn(List<Double> values) {
            addCriterion("loan_worth in", values, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthNotIn(List<Double> values) {
            addCriterion("loan_worth not in", values, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthBetween(Double value1, Double value2) {
            addCriterion("loan_worth between", value1, value2, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanWorthNotBetween(Double value1, Double value2) {
            addCriterion("loan_worth not between", value1, value2, "loanWorth");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeIsNull() {
            addCriterion("loan_begintime is null");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeIsNotNull() {
            addCriterion("loan_begintime is not null");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeEqualTo(Date value) {
            addCriterionForJDBCDate("loan_begintime =", value, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("loan_begintime <>", value, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeGreaterThan(Date value) {
            addCriterionForJDBCDate("loan_begintime >", value, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("loan_begintime >=", value, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeLessThan(Date value) {
            addCriterionForJDBCDate("loan_begintime <", value, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("loan_begintime <=", value, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeIn(List<Date> values) {
            addCriterionForJDBCDate("loan_begintime in", values, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("loan_begintime not in", values, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("loan_begintime between", value1, value2, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanBegintimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("loan_begintime not between", value1, value2, "loanBegintime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeIsNull() {
            addCriterion("loan_gettime is null");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeIsNotNull() {
            addCriterion("loan_gettime is not null");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeEqualTo(Date value) {
            addCriterionForJDBCDate("loan_gettime =", value, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("loan_gettime <>", value, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeGreaterThan(Date value) {
            addCriterionForJDBCDate("loan_gettime >", value, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("loan_gettime >=", value, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeLessThan(Date value) {
            addCriterionForJDBCDate("loan_gettime <", value, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("loan_gettime <=", value, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeIn(List<Date> values) {
            addCriterionForJDBCDate("loan_gettime in", values, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("loan_gettime not in", values, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("loan_gettime between", value1, value2, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanGettimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("loan_gettime not between", value1, value2, "loanGettime");
            return (Criteria) this;
        }

        public Criteria andLoanRateIsNull() {
            addCriterion("loan_rate is null");
            return (Criteria) this;
        }

        public Criteria andLoanRateIsNotNull() {
            addCriterion("loan_rate is not null");
            return (Criteria) this;
        }

        public Criteria andLoanRateEqualTo(Double value) {
            addCriterion("loan_rate =", value, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateNotEqualTo(Double value) {
            addCriterion("loan_rate <>", value, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateGreaterThan(Double value) {
            addCriterion("loan_rate >", value, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateGreaterThanOrEqualTo(Double value) {
            addCriterion("loan_rate >=", value, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateLessThan(Double value) {
            addCriterion("loan_rate <", value, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateLessThanOrEqualTo(Double value) {
            addCriterion("loan_rate <=", value, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateIn(List<Double> values) {
            addCriterion("loan_rate in", values, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateNotIn(List<Double> values) {
            addCriterion("loan_rate not in", values, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateBetween(Double value1, Double value2) {
            addCriterion("loan_rate between", value1, value2, "loanRate");
            return (Criteria) this;
        }

        public Criteria andLoanRateNotBetween(Double value1, Double value2) {
            addCriterion("loan_rate not between", value1, value2, "loanRate");
            return (Criteria) this;
        }

        public Criteria andProductCheckedIsNull() {
            addCriterion("product_checked is null");
            return (Criteria) this;
        }

        public Criteria andProductCheckedIsNotNull() {
            addCriterion("product_checked is not null");
            return (Criteria) this;
        }

        public Criteria andProductCheckedEqualTo(Date value) {
            addCriterionForJDBCDate("product_checked =", value, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedNotEqualTo(Date value) {
            addCriterionForJDBCDate("product_checked <>", value, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedGreaterThan(Date value) {
            addCriterionForJDBCDate("product_checked >", value, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("product_checked >=", value, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedLessThan(Date value) {
            addCriterionForJDBCDate("product_checked <", value, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("product_checked <=", value, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedIn(List<Date> values) {
            addCriterionForJDBCDate("product_checked in", values, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedNotIn(List<Date> values) {
            addCriterionForJDBCDate("product_checked not in", values, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("product_checked between", value1, value2, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductCheckedNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("product_checked not between", value1, value2, "productChecked");
            return (Criteria) this;
        }

        public Criteria andProductPublishIsNull() {
            addCriterion("product_publish is null");
            return (Criteria) this;
        }

        public Criteria andProductPublishIsNotNull() {
            addCriterion("product_publish is not null");
            return (Criteria) this;
        }

        public Criteria andProductPublishEqualTo(Date value) {
            addCriterionForJDBCDate("product_publish =", value, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishNotEqualTo(Date value) {
            addCriterionForJDBCDate("product_publish <>", value, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishGreaterThan(Date value) {
            addCriterionForJDBCDate("product_publish >", value, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("product_publish >=", value, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishLessThan(Date value) {
            addCriterionForJDBCDate("product_publish <", value, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("product_publish <=", value, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishIn(List<Date> values) {
            addCriterionForJDBCDate("product_publish in", values, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishNotIn(List<Date> values) {
            addCriterionForJDBCDate("product_publish not in", values, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("product_publish between", value1, value2, "productPublish");
            return (Criteria) this;
        }

        public Criteria andProductPublishNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("product_publish not between", value1, value2, "productPublish");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineIsNull() {
            addCriterion("loan_online is null");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineIsNotNull() {
            addCriterion("loan_online is not null");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineEqualTo(Integer value) {
            addCriterion("loan_online =", value, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineNotEqualTo(Integer value) {
            addCriterion("loan_online <>", value, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineGreaterThan(Integer value) {
            addCriterion("loan_online >", value, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_online >=", value, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineLessThan(Integer value) {
            addCriterion("loan_online <", value, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineLessThanOrEqualTo(Integer value) {
            addCriterion("loan_online <=", value, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineIn(List<Integer> values) {
            addCriterion("loan_online in", values, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineNotIn(List<Integer> values) {
            addCriterion("loan_online not in", values, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineBetween(Integer value1, Integer value2) {
            addCriterion("loan_online between", value1, value2, "loanOnline");
            return (Criteria) this;
        }

        public Criteria andLoanOnlineNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_online not between", value1, value2, "loanOnline");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loan
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable{

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table loan
     *
     * @mbggenerated
     */
    public static class Criterion implements Serializable{
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}