package com.pursebao.commons.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class Loan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.lid
     *
     * @mbggenerated
     */
    private String lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_use
     *
     * @mbggenerated
     */
    private String loanUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_amount
     *
     * @mbggenerated
     */
    private Double loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_limittime
     *
     * @mbggenerated
     */
    private Integer loanLimittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_payway
     *
     * @mbggenerated
     */
    private Integer loanPayway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_goods
     *
     * @mbggenerated
     */
    private String loanGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_worth
     *
     * @mbggenerated
     */
    private Double loanWorth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_begintime
     *
     * @mbggenerated
     */
    private Date loanBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_gettime
     *
     * @mbggenerated
     */
    private Date loanGettime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_rate
     *
     * @mbggenerated
     */
    private Double loanRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.product_checked
     *
     * @mbggenerated
     */
    private Date productChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.product_publish
     *
     * @mbggenerated
     */
    private Date productPublish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loan_online
     *
     * @mbggenerated
     */
    private Integer loanOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.lid
     *
     * @return the value of loan.lid
     *
     * @mbggenerated
     */
    public String getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.lid
     *
     * @param lid the value for loan.lid
     *
     * @mbggenerated
     */
    public void setLid(String lid) {
        this.lid = lid == null ? null : lid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.user_id
     *
     * @return the value of loan.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.user_id
     *
     * @param userId the value for loan.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_use
     *
     * @return the value of loan.loan_use
     *
     * @mbggenerated
     */
    public String getLoanUse() {
        return loanUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_use
     *
     * @param loanUse the value for loan.loan_use
     *
     * @mbggenerated
     */
    public void setLoanUse(String loanUse) {
        this.loanUse = loanUse == null ? null : loanUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_amount
     *
     * @return the value of loan.loan_amount
     *
     * @mbggenerated
     */
    public Double getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_amount
     *
     * @param loanAmount the value for loan.loan_amount
     *
     * @mbggenerated
     */
    public void setLoanAmount(Double loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_limittime
     *
     * @return the value of loan.loan_limittime
     *
     * @mbggenerated
     */
    public Integer getLoanLimittime() {
        return loanLimittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_limittime
     *
     * @param loanLimittime the value for loan.loan_limittime
     *
     * @mbggenerated
     */
    public void setLoanLimittime(Integer loanLimittime) {
        this.loanLimittime = loanLimittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_payway
     *
     * @return the value of loan.loan_payway
     *
     * @mbggenerated
     */
    public Integer getLoanPayway() {
        return loanPayway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_payway
     *
     * @param loanPayway the value for loan.loan_payway
     *
     * @mbggenerated
     */
    public void setLoanPayway(Integer loanPayway) {
        this.loanPayway = loanPayway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_goods
     *
     * @return the value of loan.loan_goods
     *
     * @mbggenerated
     */
    public String getLoanGoods() {
        return loanGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_goods
     *
     * @param loanGoods the value for loan.loan_goods
     *
     * @mbggenerated
     */
    public void setLoanGoods(String loanGoods) {
        this.loanGoods = loanGoods == null ? null : loanGoods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_worth
     *
     * @return the value of loan.loan_worth
     *
     * @mbggenerated
     */
    public Double getLoanWorth() {
        return loanWorth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_worth
     *
     * @param loanWorth the value for loan.loan_worth
     *
     * @mbggenerated
     */
    public void setLoanWorth(Double loanWorth) {
        this.loanWorth = loanWorth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_begintime
     *
     * @return the value of loan.loan_begintime
     *
     * @mbggenerated
     */
    public Date getLoanBegintime() {
        return loanBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_begintime
     *
     * @param loanBegintime the value for loan.loan_begintime
     *
     * @mbggenerated
     */
    public void setLoanBegintime(Date loanBegintime) {
        this.loanBegintime = loanBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_gettime
     *
     * @return the value of loan.loan_gettime
     *
     * @mbggenerated
     */
    public Date getLoanGettime() {
        return loanGettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_gettime
     *
     * @param loanGettime the value for loan.loan_gettime
     *
     * @mbggenerated
     */
    public void setLoanGettime(Date loanGettime) {
        this.loanGettime = loanGettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_rate
     *
     * @return the value of loan.loan_rate
     *
     * @mbggenerated
     */
    public Double getLoanRate() {
        return loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_rate
     *
     * @param loanRate the value for loan.loan_rate
     *
     * @mbggenerated
     */
    public void setLoanRate(Double loanRate) {
        this.loanRate = loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.product_checked
     *
     * @return the value of loan.product_checked
     *
     * @mbggenerated
     */
    public Date getProductChecked() {
        return productChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.product_checked
     *
     * @param productChecked the value for loan.product_checked
     *
     * @mbggenerated
     */
    public void setProductChecked(Date productChecked) {
        this.productChecked = productChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.product_publish
     *
     * @return the value of loan.product_publish
     *
     * @mbggenerated
     */
    public Date getProductPublish() {
        return productPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.product_publish
     *
     * @param productPublish the value for loan.product_publish
     *
     * @mbggenerated
     */
    public void setProductPublish(Date productPublish) {
        this.productPublish = productPublish;
    }

    @Override
    public String toString() {
        return "Loan{" +
                "lid='" + lid + '\'' +
                ", userId='" + userId + '\'' +
                ", loanUse='" + loanUse + '\'' +
                ", loanAmount=" + loanAmount +
                ", loanLimittime=" + loanLimittime +
                ", loanPayway=" + loanPayway +
                ", loanGoods='" + loanGoods + '\'' +
                ", loanWorth=" + loanWorth +
                ", loanBegintime=" + loanBegintime +
                ", loanGettime=" + loanGettime +
                ", loanRate=" + loanRate +
                ", productChecked=" + productChecked +
                ", productPublish=" + productPublish +
                ", loanOnline=" + loanOnline +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loan_online
     *
     * @return the value of loan.loan_online
     *
     * @mbggenerated
     */
    public Integer getLoanOnline() {
        return loanOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loan_online
     *
     * @param loanOnline the value for loan.loan_online
     *
     * @mbggenerated
     */
    public void setLoanOnline(Integer loanOnline) {
        this.loanOnline = loanOnline;
    }
}