package com.pursebao.commons.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class Products implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.pid
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.expected_rate
     *
     * @mbggenerated
     */
    private Double expectedRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.start_money
     *
     * @mbggenerated
     */
    private Double startMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.surplus_money
     *
     * @mbggenerated
     */
    private Double surplusMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.repayment_date
     *
     * @mbggenerated
     */
    private Date repaymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.loan_lid
     *
     * @mbggenerated
     */
    private String loanLid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_online
     *
     * @mbggenerated
     */
    private Integer productOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_introduce
     *
     * @mbggenerated
     */
    private String productIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table products
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.pid
     *
     * @return the value of products.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.pid
     *
     * @param pid the value for products.pid
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.expected_rate
     *
     * @return the value of products.expected_rate
     *
     * @mbggenerated
     */
    public Double getExpectedRate() {
        return expectedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.expected_rate
     *
     * @param expectedRate the value for products.expected_rate
     *
     * @mbggenerated
     */
    public void setExpectedRate(Double expectedRate) {
        this.expectedRate = expectedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.start_money
     *
     * @return the value of products.start_money
     *
     * @mbggenerated
     */
    public Double getStartMoney() {
        return startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.start_money
     *
     * @param startMoney the value for products.start_money
     *
     * @mbggenerated
     */
    public void setStartMoney(Double startMoney) {
        this.startMoney = startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.surplus_money
     *
     * @return the value of products.surplus_money
     *
     * @mbggenerated
     */
    public Double getSurplusMoney() {
        return surplusMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.surplus_money
     *
     * @param surplusMoney the value for products.surplus_money
     *
     * @mbggenerated
     */
    public void setSurplusMoney(Double surplusMoney) {
        this.surplusMoney = surplusMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.repayment_date
     *
     * @return the value of products.repayment_date
     *
     * @mbggenerated
     */
    public Date getRepaymentDate() {
        return repaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.repayment_date
     *
     * @param repaymentDate the value for products.repayment_date
     *
     * @mbggenerated
     */
    public void setRepaymentDate(Date repaymentDate) {
        this.repaymentDate = repaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.loan_lid
     *
     * @return the value of products.loan_lid
     *
     * @mbggenerated
     */
    public String getLoanLid() {
        return loanLid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.loan_lid
     *
     * @param loanLid the value for products.loan_lid
     *
     * @mbggenerated
     */
    public void setLoanLid(String loanLid) {
        this.loanLid = loanLid == null ? null : loanLid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_online
     *
     * @return the value of products.product_online
     *
     * @mbggenerated
     */
    public Integer getProductOnline() {
        return productOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_online
     *
     * @param productOnline the value for products.product_online
     *
     * @mbggenerated
     */
    public void setProductOnline(Integer productOnline) {
        this.productOnline = productOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_introduce
     *
     * @return the value of products.product_introduce
     *
     * @mbggenerated
     */
    public String getProductIntroduce() {
        return productIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_introduce
     *
     * @param productIntroduce the value for products.product_introduce
     *
     * @mbggenerated
     */
    public void setProductIntroduce(String productIntroduce) {
        this.productIntroduce = productIntroduce == null ? null : productIntroduce.trim();
    }
}