package com.pursebao.loan.mapper;

import com.pursebao.commons.pojo.po.Companys;
import com.pursebao.commons.pojo.po.CompanysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companys
     *
     * @mbggenerated
     */
    int countByExample(CompanysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companys
     *
     * @mbggenerated
     */
    int deleteByExample(CompanysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companys
     *
     * @mbggenerated
     */
    int insert(Companys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companys
     *
     * @mbggenerated
     */
    int insertSelective(Companys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companys
     *
     * @mbggenerated
     */
    List<Companys> selectByExample(CompanysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companys
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Companys record, @Param("example") CompanysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companys
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Companys record, @Param("example") CompanysExample example);
}