package com.pursebao.loan.mapper;

import com.pursebao.commons.pojo.po.LoanStatus;
import com.pursebao.commons.pojo.po.LoanStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoanStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_status
     *
     * @mbggenerated
     */
    int countByExample(LoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_status
     *
     * @mbggenerated
     */
    int deleteByExample(LoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_status
     *
     * @mbggenerated
     */
    int insert(LoanStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_status
     *
     * @mbggenerated
     */
    int insertSelective(LoanStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_status
     *
     * @mbggenerated
     */
    List<LoanStatus> selectByExample(LoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LoanStatus record, @Param("example") LoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LoanStatus record, @Param("example") LoanStatusExample example);
}