package com.pursebao.loan.mapper;

import com.pursebao.commons.pojo.po.Loan;
import com.pursebao.commons.pojo.po.LoanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int countByExample(LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int deleteByExample(LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int insert(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int insertSelective(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    List<Loan> selectByExample(LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    Loan selectByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Loan record, @Param("example") LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Loan record, @Param("example") LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Loan record);
}