package com.pursebao.user.mapper;

import com.pursebao.commons.pojo.po.ComAccount;
import com.pursebao.commons.pojo.po.ComAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int countByExample(ComAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int deleteByExample(ComAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int insert(ComAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int insertSelective(ComAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    List<ComAccount> selectByExample(ComAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    ComAccount selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ComAccount record, @Param("example") ComAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ComAccount record, @Param("example") ComAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComAccount record);
}