package com.pursebao.user.mapper;

import com.pursebao.commons.pojo.po.Invest;
import com.pursebao.commons.pojo.po.InvestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int countByExample(InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int deleteByExample(InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String investId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int insert(Invest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int insertSelective(Invest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    List<Invest> selectByExample(InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    Invest selectByPrimaryKey(String investId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Invest record, @Param("example") InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Invest record, @Param("example") InvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Invest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Invest record);
}