package com.pursebao.manager.pojo.po;

import java.io.Serializable;

public class Companys implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companys.cid
     *
     * @mbggenerated
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companys.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companys.case_complaint
     *
     * @mbggenerated
     */
    private String caseComplaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companys.company_address
     *
     * @mbggenerated
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table companys
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companys.cid
     *
     * @return the value of companys.cid
     *
     * @mbggenerated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companys.cid
     *
     * @param cid the value for companys.cid
     *
     * @mbggenerated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companys.company_name
     *
     * @return the value of companys.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companys.company_name
     *
     * @param companyName the value for companys.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companys.case_complaint
     *
     * @return the value of companys.case_complaint
     *
     * @mbggenerated
     */
    public String getCaseComplaint() {
        return caseComplaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companys.case_complaint
     *
     * @param caseComplaint the value for companys.case_complaint
     *
     * @mbggenerated
     */
    public void setCaseComplaint(String caseComplaint) {
        this.caseComplaint = caseComplaint == null ? null : caseComplaint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companys.company_address
     *
     * @return the value of companys.company_address
     *
     * @mbggenerated
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companys.company_address
     *
     * @param companyAddress the value for companys.company_address
     *
     * @mbggenerated
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }
}