package com.pursebao.manager.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class LoanStatus implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_status.repayment_id
     *
     * @mbggenerated
     */
    private String repaymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_status.repayment_amount
     *
     * @mbggenerated
     */
    private Double repaymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_status.repayment_time
     *
     * @mbggenerated
     */
    private Date repaymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_status.loan_id
     *
     * @mbggenerated
     */
    private String loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_status.repayment_status
     *
     * @mbggenerated
     */
    private Integer repaymentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_status
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_status.repayment_id
     *
     * @return the value of loan_status.repayment_id
     *
     * @mbggenerated
     */
    public String getRepaymentId() {
        return repaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_status.repayment_id
     *
     * @param repaymentId the value for loan_status.repayment_id
     *
     * @mbggenerated
     */
    public void setRepaymentId(String repaymentId) {
        this.repaymentId = repaymentId == null ? null : repaymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_status.repayment_amount
     *
     * @return the value of loan_status.repayment_amount
     *
     * @mbggenerated
     */
    public Double getRepaymentAmount() {
        return repaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_status.repayment_amount
     *
     * @param repaymentAmount the value for loan_status.repayment_amount
     *
     * @mbggenerated
     */
    public void setRepaymentAmount(Double repaymentAmount) {
        this.repaymentAmount = repaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_status.repayment_time
     *
     * @return the value of loan_status.repayment_time
     *
     * @mbggenerated
     */
    public Date getRepaymentTime() {
        return repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_status.repayment_time
     *
     * @param repaymentTime the value for loan_status.repayment_time
     *
     * @mbggenerated
     */
    public void setRepaymentTime(Date repaymentTime) {
        this.repaymentTime = repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_status.loan_id
     *
     * @return the value of loan_status.loan_id
     *
     * @mbggenerated
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_status.loan_id
     *
     * @param loanId the value for loan_status.loan_id
     *
     * @mbggenerated
     */
    public void setLoanId(String loanId) {
        this.loanId = loanId == null ? null : loanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_status.repayment_status
     *
     * @return the value of loan_status.repayment_status
     *
     * @mbggenerated
     */
    public Integer getRepaymentStatus() {
        return repaymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_status.repayment_status
     *
     * @param repaymentStatus the value for loan_status.repayment_status
     *
     * @mbggenerated
     */
    public void setRepaymentStatus(Integer repaymentStatus) {
        this.repaymentStatus = repaymentStatus;
    }
}